<a href="https://colab.research.google.com/github/21Maryori/Uni2_Clase1/blob/main/tarea1%2Cclase1Unid2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Arreglamos la libreria numpy de python
import numpy as np

**CREACION DE ARRAYS **

In [10]:
# 1.1 Crea un array unidimensional (vector) con 5 elementos enteros de tu elección.
array_unidimensional = np.array([1, 2, 3, 4, 5])  # El array contiene los números del 1 al 5.
print("Array unidimensional:", array_unidimensional)

Array unidimensional: [1 2 3 4 5]


In [11]:
# 1.2 Crea una matriz bidimensional (matriz) de tamaño 3x3 con valores enteros consecutivos.
matriz_bidimensional = np.arange(1, 10).reshape(3, 3) #utilice la función reshape para darle forma de matriz 3x3.

print("Matriz bidimensional:")
print(matriz_bidimensional)

Matriz bidimensional:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# 1.3 Utiliza la función np.zeros() para crear una matriz de tamaño 2x4 llena de ceros.
matriz_zeros = np.zeros((2, 4))
print("Matriz de ceros:")
print(matriz_zeros)

Matriz de ceros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
# 1.4 Utiliza la función np.ones() para crear una matriz de tamaño 3x2 llena de unos.
matriz_unos = np.ones((3, 2))
print("Matriz de unos:")
print(matriz_unos)

Matriz de unos:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
# 1.5 Utiliza la función np.random.randint() para crear una matriz de tamaño 4x4 con números enteros aleatorios entre 0 y 10.
matriz_random = np.random.randint(0, 11, size=(4, 4))
print("Matriz aleatoria:")
print(matriz_random)

Matriz aleatoria:
[[ 8  1  3  9]
 [ 4  5  2 10]
 [ 3  7  2  0]
 [10  8 10  3]]


**2.ACCESO A ELEMENTOS**

In [8]:
# Acceder al tercer elemento del vector creado en el paso 1.
tercer_elemento = vector[2]
print("Tercer elemento del vector:", tercer_elemento)

Tercer elemento del vector: 3


In [15]:
# 2.1 Accede al tercer elemento del vector creado en el paso 1.1.
tercer_elemento = array_unidimensional[2]
print("Tercer elemento del vector:", tercer_elemento)

Tercer elemento del vector: 3


In [9]:
# Acceder al elemento en la segunda fila y segunda columna de la matriz creada en el paso 2.
elemento_2_2 = matriz[1, 1]
print("\nElemento en la segunda fila y segunda columna de la matriz:")
print(elemento_2_2)


Elemento en la segunda fila y segunda columna de la matriz:
5


In [16]:
# 2.2 Accede al elemento en la segunda fila y segunda columna de la matriz creada en el paso 1.2.
elemento_2_2 = matriz_bidimensional[1, 1]
print("Elemento en la segunda fila y segunda columna:", elemento_2_2)

Elemento en la segunda fila y segunda columna: 5


**3.Propiedades de los Arrays**

In [17]:
# 3.1 Utiliza el atributo ndim para verificar la cantidad de dimensiones de la matriz creada en el paso 1.2.
dimensiones_matriz = matriz_bidimensional.ndim
print("Cantidad de dimensiones de la matriz:", dimensiones_matriz)

Cantidad de dimensiones de la matriz: 2


In [18]:
# 3.2 Utiliza el atributo shape para obtener la forma de la matriz creada en el paso 1.2.
forma_matriz = matriz_bidimensional.shape
print("Forma de la matriz:", forma_matriz)

Forma de la matriz: (3, 3)


In [19]:
# 3.3 Utiliza el atributo size para obtener el tamaño total de la matriz creada en el paso 1.2.
tamaño_matriz = matriz_bidimensional.size
print("Tamaño total de la matriz:", tamaño_matriz)

Tamaño total de la matriz: 9


**4. Operaciones Basicas**

In [27]:
# Definir las matrices aleatorias
matriz_2x2_1 = np.random.randint(0, 11, size=(2, 2))
matriz_2x2_2 = np.random.randint(0, 11, size=(2, 2))

# 4.1 Suma dos matrices de tamaño 2x2 con valores aleatorios entre 0 y 10.
suma_matrices = matriz_2x2_1 + matriz_2x2_2
print("Suma de matrices:")
print(suma_matrices)

Suma de matrices:
[[ 9  8]
 [12 16]]


In [28]:
# 4.2 Multiplica dos matrices de tamaño 3x2 y 2x3 respectivamente.
matriz_3x2 = np.random.randint(0, 11, size=(3, 2))
matriz_2x3 = np.random.randint(0, 11, size=(2, 3))
producto_matrices = np.dot(matriz_3x2, matriz_2x3)
print("Producto de matrices:")
print(producto_matrices)

Producto de matrices:
[[30  6 48]
 [35 31 64]
 [25 59 58]]


In [30]:
# 4.3 Divide una matriz de tamaño 2x2 por otra matriz de tamaño 2x2, utilizando tanto la división por elementos como la multiplicación por la inversa.
matriz_dividendo = np.random.randint(1, 11, size=(2, 2))  # Evitamos divisiones por cero
matriz_divisor = np.random.randint(1, 11, size=(2, 2))

# División por elementos
division_elementos = matriz_dividendo / matriz_divisor
print("División por elementos:")
print(division_elementos)

División por elementos:
[[10.   6. ]
 [ 0.7  1.2]]


In [31]:
# Multiplicación por la inversa
inversa_divisor = np.linalg.inv(matriz_divisor)
division_inversa = np.dot(matriz_dividendo, inversa_divisor)
print("División por inversa:")
print(division_inversa)

División por inversa:
[[2.  0.8]
 [5.  0.2]]


**5. Manipulacion de Arrays**

In [32]:
# 5.1 Utiliza la función reshape() para convertir el vector creado en el paso 1.2 en una matriz de tamaño 1x9.
matriz_1x9 = matriz_bidimensional.reshape(1, 9)
print("Matriz 1x9:")
print(matriz_1x9)

Matriz 1x9:
[[1 2 3 4 5 6 7 8 9]]


In [33]:
# 5.2 Utiliza la función flatten() para convertir la matriz creada en el paso 1.2 en un vector unidimensional.
vector_unidimensional = matriz_bidimensional.flatten()
print("Vector unidimensional:")
print(vector_unidimensional)

Vector unidimensional:
[1 2 3 4 5 6 7 8 9]


**6. Operaciones Estadísticas:**

In [34]:
# 6.1 Calcula la suma de todos los elementos de la matriz creada en el paso 1.2.
suma_total = np.sum(matriz_bidimensional)
print("Suma de todos los elementos de la matriz:", suma_total)

Suma de todos los elementos de la matriz: 45


In [35]:
# 6.2 Calcula la media de cada fila de la matriz creada en el paso 1.2.
medias_filas = np.mean(matriz_bidimensional, axis=1)
print("Media de cada fila de la matriz:")
print(medias_filas)

Media de cada fila de la matriz:
[2. 5. 8.]


**7. Indexación y Rebanado**

In [36]:
# 7.3 Imprime la primera fila de la matriz creada en el paso 1.2.
primera_fila = matriz_bidimensional[0]
print("Primera fila de la matriz:")
print(primera_fila)

Primera fila de la matriz:
[1 2 3]


In [37]:
# 7.4 Imprime las primeras dos columnas de la matriz creada en el paso 1.2.
primeras_dos_columnas = matriz_bidimensional[:, :2]
print("Primeras dos columnas de la matriz:")
print(primeras_dos_columnas)

Primeras dos columnas de la matriz:
[[1 2]
 [4 5]
 [7 8]]


**8. Ejecicio Adicional**

In [38]:
# Define una matriz de tamaño 4x4 con valores aleatorios
matriz_4x4 = np.random.randint(0, 101, size=(4, 4))  # Valores aleatorios entre 0 y 100
print("Matriz 4x4:")
print(matriz_4x4)

Matriz 4x4:
[[41 54  1 53]
 [80  0 39 92]
 [24 22 94 11]
 [ 9 45 45 15]]


In [41]:
# Encuentra el valor máximo y su posición
maximo_valor = np.max(matriz_4x4)
posicion_maximo = np.unravel_index(np.argmax(matriz_4x4), matriz_4x4.shape)
# Encuentra el valor mínimo y su posición
minimo_valor = np.min(matriz_4x4)
posicion_minimo = np.unravel_index(np.argmin(matriz_4x4), matriz_4x4.shape)

print("\nValor máximo:", maximo_valor)
print("Posición del valor máximo:", posicion_maximo)
print("\nValor mínimo:", minimo_valor)
print("Posición del valor mínimo:", posicion_minimo)


Valor máximo: 94
Posición del valor máximo: (2, 2)

Valor mínimo: 0
Posición del valor mínimo: (1, 1)
